name: Draw ZMK keymaps
on:
  workflow_dispatch:
  push:
    paths:
      - "config/**"
      - ".github/workflows/draw-keymaps.yml"

permissions:
  contents: write

jobs:
  draw:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: caksoylar/keymap-drawer-action@v3
        with:
          keymap_patterns: "config/corne.keymap"
          output_folder: "keymap-drawer"
